Covers
okkamien/okkamien-webapp pull request #23
Opened 2024-08-01 15:23 UTC by 221Michal

# Add covers

Add covers on all page

## Changelog

- Add Cover components (carousel home page)
- Add Cover-image for image with overlay (with no children small view for another page)
- Add cover-item for event details in home page carousel

2024-08-03 15:53 UTC, piotrkonowrocki requested changes
Karuzela na stronie głównej wygląda super, propsuję. Mam tylko jedną uwagę. Imo karuzela powinna się zapętlać i zawsze powinno być dostępne przewijanie w obydwie strony. Chyba, że to wymaganie pana dyrektora, żeby tak zrobić, to wtedy do poprawy inna rzecz - strzałki poza samym opacity 0 powinny mieć pointer events none, bo w w tej chwili można najechać w miejsce po strzałce i myszka zostaje jako pointer.

2024-08-05 22:30 UTC, piotrkonowrocki requested changes

2024-08-05 22:30 UTC, piotrkonowrocki commented on package.json
> +    "embla-carousel-fade": "^8.1.6",
Bez ^, instalujemy tylko konkretne wersje.

2024-08-07 08:06 UTC, 221Michal commented on package.json
> +    "embla-carousel-fade": "^8.1.6",
poprawione co myślisz o tym by zmienić author tak by było, że ja też robiłem tą stronę? :D teraz patrzę, że tylko Ty jesteś ujęty :D

2024-08-10 12:46 UTC, piotrkonowrocki approved these changes

2024-08-10 13:07 UTC, merged