Feature/footer
okkamien/okkamien-webapp pull request #9
Opened 2024-06-02 12:59 UTC by 221Michal

# PR title

Add footer

## Changelog

- Add`LogoSection`
- Create `Accordion` Component
- Add `LinkSection`

2024-06-12 14:02 UTC, piotrkonowrocki requested changes
Ogólna uwaga do kodu, nie jestem w stanie wskazać konkretnych miejsc, ale to coś co ogólnie wyłania się z sprawdzenia co się dzieje w devtoolsach.

Mam trochę poczucie, że układ jest trochę chaotyczny, w wielu miejscach do odstępów używane są paddingi zamiast marginesów lub marginesy zamiast gapów z flexa. Do tego ogólne odstępy elementów od siebie nie wynikają z jednej wartości, tylko czasem z sumy paddingów/marginesów kilku zagnieżdżonych elementów. Np. akordeon z linkami ma malutki margines z lewej strony, a jego rodzic dodatkowy, większy - czemu nie połączyć ich w jeden? Zamiast stosowania skomplikowanego layoutu opartego od max/min szerokości może da się to przestawić na css grid z wykorzystaniem `grid-template-columns`? Byłoby o wiele czytelniej i przejrzyściej, a patrząc na sam projekt wygląda mi to na książkowy przykład gdzie można użyć grida.

2024-06-12 15:50 UTC, 221Michal commented on app/components/layout/componets/footer/LinksSections.tsx
> +      pr: [0, 52],
no tylko jest dość daleko do najbliższych breaków 44 lub 64 dużo to zmienia, jak żyć?

2024-06-12 15:59 UTC, 221Michal commented on app/components/layout/componets/footer/LogoSection.tsx
> +        label: 'Tile-image',
tak tak bo próbowałem tam to logo ogarnąć ale się poddałem

2024-06-12 16:13 UTC, 221Michal commented on app/components/layout/componets/footer/SecondSection.tsx
> +        <Box tag="li" key={i} cs={{padding: [`${theme.spacing.xxs}px ${theme.spacing.xs}px`, `${theme.spacing.xxs}px 0`], mb: [4, 0]}}>
wejdzie jak zrobie pusha

2024-06-12 16:13 UTC, 221Michal commented on app/components/layout/componets/footer/LinksSections.tsx
> +          paddingBottom: theme.spacing.xxs,
wejdzie jak zrobie pusha

2024-06-12 16:13 UTC, 221Michal commented on app/components/layout/componets/footer/LinksSections.tsx
> +      <Text cs={{color: theme.color.brand400, pb: theme.spacing.xs, fontSize: theme.font.size.base}}>Gdzie nas znajdziesz</Text>
wejdzie jak zrobie pusha

2024-06-12 16:13 UTC, 221Michal commented on app/components/layout/componets/footer/LinksSections.tsx
> +      maxWidth: ['unset', 300],
wejdzie jak zrobie pusha

2024-06-12 16:14 UTC, 221Michal commented on app/components/layout/componets/footer/LinksSections.tsx
> +    <FirstSection key="first-section" />
wywaliłem wszystko bez komponentów wejdzie po pushu

2024-06-12 16:14 UTC, 221Michal commented on app/components/layout/componets/footer/ExpandableArrow.tsx
skasuje się po pushu

2024-06-12 16:14 UTC, 221Michal commented on app/components/layout/componets/footer/Accordion.tsx
> +        <Text
wejdzie jak zrobie pusha

2024-06-12 16:14 UTC, 221Michal commented on app/components/layout/componets/footer/Accordion.tsx
> +        cs={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer'}}
wejdzie jak zrobie pusha

2024-06-12 16:14 UTC, 221Michal commented on app/components/layout/componets/footer/Accordion.tsx
> +  })
wejdzie jak zrobie pusha

2024-06-12 16:15 UTC, 221Michal commented on app/components/layout/componets/footer/Accordion.tsx
> +  const expandableItems = useRef<HTMLInputElement>()
wejdzie jak zrobie pusha

2024-06-12 16:16 UTC, 221Michal commented on .gitignore
> +/.vscode/settings.json
dodana secja editors, bo w repo nie ma nic .vscode, a mnie wkurwia, że settigngs mi wywala jak sobie dodałem

2024-06-12 16:16 UTC, 221Michal commented on app/components/layout/componets/footer/SecondSection.tsx
> +      <AccordionMenu />
wywalone po pushu

2024-06-12 16:17 UTC, 221Michal commented on app/components/layout/componets/footer/SecondSection.tsx
> +      pr: [0, 52],
jest bardzo daleko do wartości u nas w theme `44` lub `64` dużo zmienia wizualnie

2024-06-12 16:17 UTC, 221Michal commented on app/styles/theme.ts
> +    brand400: colors.blueEastBay,
podpowiesz jakiś?

2024-06-12 16:57 UTC, 221Michal commented on app/components/layout/componets/footer/LogoSection.tsx
> +      <Link href="/" legacyBehavior passHref>
wejdzie po pushu

2024-06-13 12:38 UTC, piotrkonowrocki commented on .gitignore
> +/.vscode/settings.json
Elegancko, a czy zamiast `/.vscode/settings.json` mógłbyś zmienić, żeby było po prostu `.vscode`? Wtedy wykluczymy wszystko, co potencjalnie może wygenerować VS Code.

2024-06-13 12:41 UTC, piotrkonowrocki commented on app/components/layout/componets/footer/Accordion.tsx
> +        <Text
Nie do końca o to chodziło. Miałem tutaj na myśli, żeby zastąpić cały ten fragment
```ts
<Text
  tag="h3"
  variant="h6"
  cs={{
	color: theme.color.brand400,
	pb: theme.spacing.xxs,
	pt: [theme.spacing.xxs, 0],
	fontSize: theme.font.size.base,
  }}
>
  {title}
</Text>
```
Samym
```ts
{title}
```
Dzięki temu jako kilkalną część akordeona można przekazać cokolwiek z niezależnym stylowaniem - nadal myślę tutaj o filtrach na mobilke.

2024-06-13 12:41 UTC, 221Michal commented on .gitignore
> +/.vscode/settings.json
tam nie ma za bardzo co być więcej z tego co kojarzę

2024-06-13 12:42 UTC, piotrkonowrocki commented on app/components/layout/componets/footer/ExpandableArrow.tsx
No to teraz możesz zmerdżować `main` do siebie i użyć już tego komponentu po moich przeróbkach 😆

2024-06-13 12:42 UTC, 221Michal commented on app/components/layout/componets/footer/Accordion.tsx
> +        <Text
aaaaa ma to więcej sensu 👯‍♂️

2024-06-13 12:43 UTC, piotrkonowrocki commented on app/components/layout/componets/footer/LinksSections.tsx
> +      pr: [0, 52],
Skonsultować z Patrycją? Może przejście na css grida sprawi, że nie będzie potrzeby pisać tylu paddingów i marginesów ręcznie i szerokości dopasują się same, z proporcji?

2024-06-13 12:44 UTC, piotrkonowrocki commented on app/dictionaries/site.dictionary.ts
> +export const navigationAnotherLinks = [
Tak.

Ale zmian nie widzę 😆

2024-06-13 12:46 UTC, piotrkonowrocki commented on app/components/layout/componets/footer/SecondSection.tsx
> +      pr: [0, 52],
To samo co w https://github.com/okkamien/okkamien-webapp/pull/9#discussion_r1638143375, myślę że docelowo jest do ogarnięcia.

2024-06-13 12:50 UTC, 221Michal commented on app/styles/theme.ts
> +    brand400: colors.blueEastBay,
tytuły w sekcjach w footerze

2024-06-13 12:51 UTC, 221Michal commented on app/dictionaries/site.dictionary.ts
> +export const navigationAnotherLinks = [
xDDDDDD

2024-06-13 12:51 UTC, 221Michal commented on app/dictionaries/site.dictionary.ts
> +export const navigationAnotherLinks = [
źle przeczytałem :D

2024-06-13 13:12 UTC, piotrkonowrocki commented on app/components/layout/componets/footer/LogoSection.tsx
> +        label: 'Tile-image',
Logo poprawione.

2024-06-13 16:02 UTC, 221Michal commented on app/dictionaries/site.dictionary.ts
> +export const navigationAnotherLinks = [
poprawione

2024-06-13 16:03 UTC, 221Michal commented on app/components/layout/componets/footer/ExpandableArrow.tsx
użyłem :)

2024-06-27 00:25 UTC, piotrkonowrocki approved these changes

2024-06-27 00:25 UTC, okkamien approved these changes

2024-06-27 00:26 UTC, merged